export const shoes = [
    {
        id: 1,
        name: 'Nike',
        image: 'nike.PNG',
        description: 'A just do it Shoe',
        category: 'Athletic',
        price: 60,
    },
    /*{
id: 2,
name: 'Adidas',
image: 'adidas.PNG',
description: 'A stripes kind of Shoe',
category: 'Athletic',
price: 50,
},
{
id: 3,
name: 'Puma',
image: 'puma.PNG',
description: 'A feline Shoe',
category: 'Athletic',
price: 30,
},
{
id: 4,
name: 'Jordan',
image: 'jordan.PNG',
description: 'A last dance kind of Shoe',
category: 'Athletic',
price: 300,
},
{
id: 5,
name: 'Tods',
image: 'tods.PNG',
description: 'A driving Shoe',
category: 'Smart',
price: 400,
},
{
id: 6,
name: 'Clarks',
image: 'clarks.PNG',
description: 'A proper  Shoe',
category: 'Smart',
price: 120,
},
];*/